### ISSUE TITLE
Doesn't work with Nuxt 2.15.3

### ISSUE THREAD

**Issue by apithy-isidro-martinez** [nuxt/components#168]
It was working well, and just upgrade to Nuxt 2.15.3 from Nuxt 2.14.12 and in the browser shows errror that the components have not been registered

**Comment by pi0** [comment]
Hi @apithy-isidro-martinez. A reproduction would be nice. But I guess you might check [migration guide](https://github.com/nuxt/components#migration-guide). A markdown file (`.nuxt/components/readme.md`) is being generated which you can check if any naming changed.

**Comment by apithy-isidro-martinez** [comment]
According to the guide, then I have to specify the path of the folders that contain my components?
![image](https://user-images.githubusercontent.com/74619952/111367581-7ef38800-865a-11eb-966c-5c1e6e35ed6b.png)

**Comment by pi0** [comment]
If you don't want component names to be prefixed (ie `BaseAlert` and `NavigationLink`), yes. Or you can disable `pathPrefix` for v1 behavior:

```js
components: [
  { path: '~/components', pathPrefix: false }
]
```

**Comment by WanyoikeJ** [comment]
I have the same issue, Nearly the entire project was based in components auto discover but now its not working. am in version 2.15.3

**Comment by kwolniak** [comment]
IDK if it's the same problem but I have this error after update to nuxt 2.15.* During starting dev server:
```
TypeError: Cannot read property 'use' of undefined


        at WebpackBundler.<anonymous> (/usr/local/lib/node_modules/nuxt/node_modules/@nuxt/components/dist/index.js:114:17)
at next (node_modules/@nuxt/utils/dist/utils.js:659:27)
at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:674:12)
at WebpackClientConfig.extendConfig (node_modules/@nuxt/webpack/dist/webpack.js:1509:37)
at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:1544:50)
at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:1708:26)
at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack/dist/webpack.js:2016:19)
at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2023:12)
at Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:30)
at async Object._buildDev (/usr/local/lib/node_modules/nuxt/node_modules/@nuxt/cli/dist/cli-dev.js:106:5)
at async Object.startDev (/usr/local/lib/node_modules/nuxt/node_modules/@nuxt/cli/dist/cli-dev.js:64:7)
at async Object.run (/usr/local/lib/node_modules/nuxt/node_modules/@nuxt/cli/dist/cli-dev.js:51:5)
at async NuxtCommand.run (/usr/local/lib/node_modules/nuxt/node_modules/@nuxt/cli/dist/cli-index.js:2811:7)
```

**Comment by sa8ab** [comment]
Fixed to previous behavior by changing
`components: true`
to
```components: [
  { pathPrefix: false }
]```

**Comment by pi0** [comment]
I can confirm @sa8ab solution. If prefixing is not desired, can be disabled. Sorry for the inconvenience of v2 breaking changes added by 2.15... (new docs will make it better for `pathPrefix` usage)
