### ISSUE TITLE
[BUG] Error: Can't resolve 'node_modules/@scope/my-module

### ISSUE THREAD

**Issue by tebaly** [nuxt/components#204]
**Describe the bug**
Hello. I use Nuxt @ v2.15.6 and set components from _'path: 'node_modules/@scope/my-module/components'_ (pathPrefix: false)

## It works
On development. All components listed on _.nuxt/components/readme.md_ BUT

## ERROR in ./pages/ ... Module not found: Error: Can't resolve 'node_modules/@scope/my-module/components/some-component.vue

On buil for prod
  
## Why? How to fix it?

**Comment by tebaly** [comment]
I will try within a few hours

**Comment by tebaly** [comment]
> Do you mind providing a reproduction?

# Hello

I create simple test component https://github.com/tebaly/nc-test-dep
I run _npx create-nuxt-app nc-build_  - create test project (default)
I run _npm install https://github.com/tebaly/nc-test-dep_ - to install simple test component dependency
I create **progect repo** https://github.com/tebaly/nc-build

---

Development - OK
Build - 

```bash
ERROR in ./pages/index.vue
Module not found: Error: Can't resolve 'node_modules/nc-test-dep/components/Test.vue' in '/home/***/SERVERS/test/nc-build/pages'
 @ ./pages/index.vue 23:115-170
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js

 FATAL  Nuxt build error                                                                      12:09:35

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:110:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nc-build@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nc-build@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/***/.npm/_logs/2021-06-06T09_09_35_488Z-debug.log


```

**Comment by tebaly** [comment]
What am I doing wrong?

**Comment by tebaly** [comment]
Hi. Say something. Autoloading of components with standard settings does not work.

**Comment by evdevru** [comment]
Create symbolic link on package folder in "components" folder. After that build will be successful.

**Comment by tebaly** [comment]
This is HOTFIX - if this is a BUG, why doesn't anyone fix it?

**Comment by tebaly** [comment]
@pi0 @kevinmarrec @Atinux - can you fix it?

**Comment by command-tab** [comment]
I'm running into this with Nuxt 2.15.8. When I add a scoped module in `nuxt.config.js` like this...

```
components: [
  '~/components', // shortcut to { path: '~/components' }
  { path: 'node_modules/@pixar/redacted-component-name', pathPrefix: false }
],
```

...it works in development without issue. But when I run `yarn run build` to invoke `nuxt build`, it errors out with:

```
ERROR in ./components/Navbar.vue
Module not found: Error: Can't resolve 'node_modules/@pixar/redacted-component-name/src/components/Redacted.vue' in '/Users/redacted/Projects/redacted/app/components'
 @ ./components/Navbar.vue 22:41-111
 @ ./layouts/default.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js
```

A workaround is to manually import and declare components in the consuming page's `components` section, but that defeats the purpose of nuxt/components :) According to the error, the build process is looking in the app's `components` directory, which makes me think it's not respecting the `pathPrefix: false` option like dev does, but that's just a guess.

**Comment by command-tab** [comment]
That works! Thank you! 🙌🏻 

For others, be sure to point `path` to the directory containing the component's `package.json` so the loader can find the `main` entry point described within.
